### ISSUE TITLE
Warning: Could not find any test files matching pattern: lcovonly

### ISSUE THREAD

**Issue by 0vulns** [xc0d3rz/hackerone#1]
```bash
> hackerone@1.0.0 test-co /home/travis/build/xc0d3rz/hackerone
> PATH=$(npm bin):$PATH  && istanbul cover _mocha --reporter lcovonly -- -R spec -t 15000 && codecov
Warning: Could not find any test files matching pattern: lcovonly
No test files found
No coverage information was collected, exit without writing coverage information
```
[For more](https://travis-ci.org/xc0d3rz/hackerone/builds/249044914)

**Comment by Aarbel** [comment]
hi @xc0d3rz ! How did you fixed this issue ? Have same problem but can't find how to fix it, thanks :)

**Comment by 0vulns** [comment]
Hi @Aarbel 
I fixed it by changing `--reporter lcovonly` to `--reporter test` for more please see 82c75e037ad25647590d42cc9767e86b2a89311f

**Comment by Aarbel** [comment]
thanks ;)
